spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  RabbitMQ:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0



server:
  port: 8080